src/gui.rs, src/gui/mod_list.rs
=> Enable and disable mods from mod list

src/gui/mod_list.rs
=> Add column headings

src/gui.rs, src/gui/mod_list.rs, src/style.rs
=> Tweak menu bar styling/organisation

src/gui/mod_list.rs, src/style.rs
=> Column separators (rules/borders)

src/gui/mod_list.rs, src/style.rs
=> Alternate background colour of each entry in mod list

src/gui/mod_list.rs, src/style.rs
=> Highlight currently selected mod entry

src/gui/mod_list.rs
=> Add additional metadata to description box

src/gui.rs, src/gui/settings.rs, src/gui/settings/vmparams.rs
=> Let user modify vmparams file from within app

src/gui/install.rs, src/gui/mod_list.rs
=> Mod upgrading/mod ID collision checking

src/gui/mod_list.rs
=> Provide sorting on mods list columns

src/gui/install.rs, src/gui/mod_list.rs
Handing the temporary folder off to the standard install code was not
correct, as the install function has a number of embedded assumptions
(ie: the given folder is reasonably named, or has a nested child folder
that actually contains the mod. It could probably do with changed
anyway...).
Fixed by using custom handling of ID collisions in the match branch of
the mod_list handler, which just runs a rename and deletes any empty
parent directories that were left behind.
=> Fix handling of existing ID collision/upgrading

Cargo.lock, Cargo.toml, src/gui/install.rs, src/gui/mod_list.rs, src/style.rs
Fixes #45
Adds clickable forum links to the mod description box. Clicking them should open the link in the system default browser.
=> Add clickable forum links to description

src/gui.rs, src/gui/mod_list.rs, src/gui/settings.rs
Apply writes out settings values, but does not close the settings page.
=> Add apply button to settings

src/gui/mod_list.rs
Fixes #47
Adds a new dropdown/menu named `Tools`. It features enable all,
disable all, and filter by enabled, disabled, mods with updates
available, mods that failed update checks, mods with no version check
support, and no filter. Finally, an option to refresh the mod list, for
cases where the mod list folder on disk changes.
=> Additional controls

src/gui/install.rs, src/gui/mod_list.rs
=> Delete temp mod folder left behind on err/decline

src/archive_handler.rs, src/gui/mod_list.rs
=> Add debounce to install messages

src/gui.rs, src/style.rs
=> Highlight "Apply" button in settings when a change is made

src/gui/mod_list.rs
=> Fix mod update tooltip text

src/gui/mod_list.rs
=> Fix sorting on mod version header

src/gui/mod_list.rs
=> Refresh mod list on settings close only if install dir changes

Cargo.lock, Cargo.toml, src/gui.rs, src/gui/dialogs/dialog.rs, src/gui/dialogs/macos.rs, src/gui/dialogs/other.rs, src/gui/mod_list.rs, src/gui/util.rs
- Fix archives not showing in archive selector sometimes
- Prevent unnecessary mod list refreshes
- Sort by version uses mod name as secondary sort
- Add search functionality
- Persist last browsed directory across app uses/instances/launches
=> Version 0.4.4

src/gui/mod_list.rs
=> Add "Open in File Manager" button to mod entries

src/gui.rs, src/gui/mod_list.rs, src/gui/settings.rs
=> Add checking for .git folders to prevent destruction of mod development environments

src/gui/mod_list.rs
=> Show currently installed/active mod count

Cargo.lock, Cargo.toml, src/gui/installer.rs, src/gui/mod_list.rs
0.5.1 broke mod installation but at least fixed auto-updates....
This fixes the bug introduced by the fix........
=> v0.5.2 Fix the fix

.gitignore, Cargo.lock, Cargo.toml, src/app.rs, src/app/controllers/app_controller.rs, src/app/controllers/install_controller.rs, src/app/controllers/mod.rs, src/app/controllers/mod_list_controller.rs, src/app/installer.rs, src/app/mod_description.rs, src/app/mod_entry.rs, src/app/mod_list/headings.rs, src/app/settings.rs, src/icons/mod.rs, src/main.rs, src/util.rs, src/webview.rs
Utilising system webview implementations, we can provide our own "browser" through which we can capture user browser interactions, and thus intercept downloads from mod forums and thus "directly" install mods from just links without any other infrastructure.
=> Implement mod browser

src/app/mod_description.rs
=> Mod Description section does not scroll when overflowed

src/main.rs
=> Add MOSS version somewhere visible

Cargo.lock, rustfmt.toml, src/app.rs, src/main.rs, src/webview.rs, webview-subsystem/Cargo.toml, webview-subsystem/src/init.js, webview-subsystem/src/lib.rs
=> Fix webview failing to download/install on macOS

src/app.rs, src/main.rs
=> Webview downloads fail on Linux due to a persist error

src/app/settings.rs
=> VMParam edits are not consistently saved

src/app.rs, src/app/mod_entry.rs, src/app/mod_repo.rs, src/app/settings.rs
=> Auto updating is offered when the local version is higher than the remote version

src/app/mod_entry.rs
=> Fix versions being wrong in list for no-vc mods
